### ISSUE TITLE
animate_order does not work

### ISSUE THREAD

**Issue by jimparis** [vmario89/mightyscape-1.X#1]
The `animate_order` extension fails to run with error "Error. Target file does not exist!".  It's looking for a file `animate_order.html` which does not exist in the repository and is generated later in the script.  Reverting b67f0c8136b36230620a5f632f64f3e554516961 fixes it.

**Comment by vmario89** [comment]
Hi, sorry for the delay - have been absent for a while. I fixed the issue with commit https://github.com/vmario89/mightyscape-1.X/commit/bdf4dc145a733b20a2d0f7924537eb3d8ed0cadd

regards, Mario
