### ISSUE TITLE
Sub Menu Entries No Show Ubuntu 20.04 Inkscape 0.92

### ISSUE THREAD

**Issue by InkyDrip** [vmario89/mightyscape-1.X#2]
Hi,

Like your compilation of extensions.

However, to produce the necessary sub menu entries in Inkscape 0.92 on Ubuntu 20.04 I had to batch edit all of the .inx files:

Replacing '**<command location="inx"**' with '**<command reldir="extensions"**'.

**Comment by vmario89** [comment]
Hi @InkyDrip , 

thanks for your feedback. This collection is not compatible with Inkscape 0.92.* versions. Please do not do that. Python APIs, python version (2 to 3) and a lot more changed. Most of the extensions will just fail in Inkscape versions lower than 1.x

regards, Mario
