### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'box.svg'

### ISSUE THREAD

**Issue by Deltaplc** [vmario89/mightyscape-1.X#3]
Good morning
I have two pc with win 10
I installed the same python and the same version of inkscape.
In one the boxes.py extensions work in the second they give me an error.
Do you have some advice?
Thanks
Davide

**Comment by vmario89** [comment]
Hi. seems that in one of your installations boxes.py is not able to store the generated tempoary file, which is then imported into inkscape. Please check if your antivirus prohibits to write in the installation directory. i changed boxes py proxy to use temporary directory. could you try again? i pushed some recent commit: https://github.com/vmario89/mightyscape-1.X/commit/aecbd00c1e29231f7c59ac75622adc2d4c6b1e1e

**Comment by Deltaplc** [comment]
Thank you so much for your response so fast!
I tried with the update you made .... now this error comes out!
I also uninstalled the antivirus!

There was no C:\Users\Davide\AppData\Local\Temp\box.svg output generated. Cannot continue. Command was:
boxes roundedbox --x 100 --y 100 --h 100 --outside true --radius 15 --wallpieces 1 --edge_style f --top closed --thickness 3 --tabs 0 --debug false --labels true --reference 100 --burn 0.10000000149011612 --FingerJoint_angle 90 --FingerJoint_style rectangular --FingerJoint_surroundingspaces 2 --FingerJoint_edge_width 1 --FingerJoint_finger 2 --FingerJoint_play 0 --FingerJoint_space 2 --FingerJoint_width 1 --Flex_stretch 1.0499999523162842 --Flex_connection 1 --Flex_distance 0.5 --Flex_width 5 --output C:\Users\Davide\AppData\Local\Temp\box.svg C:\Users\Davide\AppData\Local\Temp\box.svg

**Comment by vmario89** [comment]
mmhh does this error appear for other boxes types too? or does it appear for rounded box only? i think there are some differences in boxes.exe for Windows and the easy installation on Linux. The inx files may differ for Windows (so i need to recompile most recent boxes.py version). But this should affect only less extensions

**Comment by Deltaplc** [comment]
The problem is on all types of "Boxes.py".
I have installed other extensions of your package like "box_maker_generic_generator" and those have no problem, they work perfectly.
I do not understand....

**Comment by Deltaplc** [comment]
Hello
I have something new!
When you told me that it lacks permissions you put a flea in my ear ...... I tried running inkscape as an administrator and it magically works!

Do you have any advice for me about it?
Thank you for your support!

**Comment by vmario89** [comment]
hmmm what happens if you run from your cmd shell instead using inkscape? Does this give permission error too, if you are not an admin? I think it could have to do sth. with the execution of subprocesses.

`boxes roundedbox --x 100 --y 100 --h 100 --outside true --radius 15 --wallpieces 1 --edge_style f --top closed --thickness 3 --tabs 0 --debug false --labels true --reference 100 --burn 0.10000000149011612 --FingerJoint_angle 90 --FingerJoint_style rectangular --FingerJoint_surroundingspaces 2 --FingerJoint_edge_width 1 --FingerJoint_finger 2 --FingerJoint_play 0 --FingerJoint_space 2 --FingerJoint_width 1 --Flex_stretch 1.0499999523162842 --Flex_connection 1 --Flex_distance 0.5 --Flex_width 5 --output C:\Users\Davide\AppData\Local\Temp\box.svg C:\Users\Davide\AppData\Local\Temp\box.svg`

**Comment by Deltaplc** [comment]
Hello
I did other tests: with the new version you made it doesn't even work as an administrator, with the previous one it works, but not with all the "Boxes.py". With "boxes.py.UniversalBox", for example, it doesn't work and always has an authorization error.
With the (older) version that I have on another PC, everything works with administrator authorization.

>hmmm cosa succede se esegui dalla tua shell cmd invece di usare inkscape?<

I did not understand the question ... I am not really a genius with these extensions.

**Comment by vmario89** [comment]
i know, its sometimes a bit tedious :-/ Please try to run that boxes.exe in your extension folder manually by executing the command in a cmd shell. You do not need to start Inkscape to check if your computer is able to run boxes.py correctly. This way you can better find out if its a problem with Windows permissions, boxes.py, python or Inkscape.

**Comment by Deltaplc** [comment]
Good morning
I don't know if I am able to use cmd correctly, please excuse my ignorance :(.
Can you give me an example?
I tried to do this but I don't know if it's correct!

>
(c) Microsoft Corporation. Tutti i diritti sono riservati.

C:\Windows\system32>C:\Users\Davide\Desktop\Varie inkscape\mightyscape-1.X-master\mightyscape-1.X-master\extensions\fablabchemnitz\boxes.py
"C:\Users\Davide\Desktop\Varie" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

C:\Windows\system32>C:\Users\Davide\AppData\Local\Temp\box.svg C:\Users\Davide\AppData\Local\Temp\box.svg
"C:\Users\Davide\AppData\Local\Temp\box.svg" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

<

**Comment by vmario89** [comment]
hi,

when you are in the shell, please type the following:

```
cd C:\Users\Davide\Desktop\Varie inkscape\mightyscape-1.X-master\mightyscape-1.X-master\extensions\fablabchemnitz\boxes.py\

boxes roundedbox --x 100 --y 100 --h 100 --outside true --radius 15 --wallpieces 1 --edge_style f --top closed --thickness 3 --tabs 0 --debug false --labels true --reference 100 --burn 0.10000000149011612 --FingerJoint_angle 90 --FingerJoint_style rectangular --FingerJoint_surroundingspaces 2 --FingerJoint_edge_width 1 --FingerJoint_finger 2 --FingerJoint_play 0 --FingerJoint_space 2 --FingerJoint_width 1 --Flex_stretch 1.0499999523162842 --Flex_connection 1 --Flex_distance 0.5 --Flex_width 5 --output C:\Users\Davide\AppData\Local\Temp\box.svg C:\Users\Davide\AppData\Local\Temp\box.svg
```
the first command declares your working directory, the second one executes the boxes.exe with some parameters. If it works it should generate a box.svg file in C:\Users\Davide\AppData\Local\Temp\box.svg or else it should give you some error.

**Comment by Deltaplc** [comment]
Ciao
Ho fatto come mi hai detto....non da errore ma non genera nessun file in
 C:\Users\Davide\AppData\Local\Temp\box.svg

**Comment by vmario89** [comment]
i have no solution for windows yet. I think i will need to rework this by removing the .exe proxy and use the recent python git project as local python module, but its a little bit more work so no quick fix for next days. i will keep open this issue to remind myself

have a look at https://florianfesti.github.io/boxes/html/install/windows.html#native
```
pip3 install markdown affine
python scripts\boxes roundedbox
```

**Comment by Deltaplc** [comment]
Good morning
Sorry I'm late I had some problems.
Thank you so much for your help!
Greetings
David

**Comment by sosher** [comment]
Hi, Are there any news regarding this issue ? 

Thanks

**Comment by Deltaplc** [comment]
Good morning.
Thank you for your interest .....!
Yes, I solved it by reinstalling Inkscape and python, I probably didn't install them correctly.
I also tried to follow your advice and now everything works!
Thank you so much for your help!
Greetings

**Comment by dokh** [comment]
Just a FYI on troubleshooting the issue.
When I ran `boxes <boxname>` without any parameter, a box.svg is created in the boxes.py directory.

Tested it with `boxes roundedbox` and `boxes CoffeeCapsuleHolder`

Then I tried variations to the parameters list:
`boxes roundedbox --x 200` ==> no luck
`boxes roundedbox --x200` ==> no luck
`boxes roundedbox --x=200` ==> TADAA! New box.svg with correct x dimension

Next I tried 
`boxes roundedbox --x=200 --y=200 --h=200 --outside=true --radius=20 --wallpieces=1 --edge_style=f --top=closed --thickness=3 --tabs=0 --debug=false --labels=true --reference=100 --burn=0.1 --FingerJoint_angle=90 --FingerJoint_style=rectangular --FingerJoint_surroundingspaces=2 --FingerJoint_edge_width=1 --FingerJoint_finger=2 --FingerJoint_play=0 --FingerJoint_space=2 --FingerJoint_width=1 --Flex_stretch=1.05 --Flex_connection=1 --Flex_distance=0.5 --Flex_width=5`
but it failed.

So I cycled thru all params removing one at a time untill  it created a box.svg with:
`boxes roundedbox --x=200 --y=200 --h=200 --outside=true --radius=20 --wallpieces=1 --edge_style=f --top=closed --thickness=3 --tabs=0 --debug=false`
but failed with:
`boxes roundedbox --x=200 --y=200 --h=200 --outside=true --radius=20 --wallpieces=1 --edge_style=f --top=closed --thickness=3 --tabs=0 --debug=false --labels=true`

In the end the full command with equal signs and removed --labels param worked:
`boxes roundedbox --x=200 --y=200 --h=200 --outside=true --radius=20 --wallpieces=1 --edge_style=f --top=closed --thickness=3 --tabs=0 --debug=false --reference=100 --burn=0.1 --FingerJoint_angle=90 --FingerJoint_style=rectangular --FingerJoint_surroundingspaces=2 --FingerJoint_edge_width=1 --FingerJoint_finger=2 --FingerJoint_play=0 --FingerJoint_space=2 --FingerJoint_width=1 --Flex_stretch=1.05 --Flex_connection=1 --Flex_distance=0.5 --Flex_width=5 --output=C:\Users\koen\AppData\Local\Temp\box.svg
`

Next I adapted the boxes_proxy.py to reflect that.
This is the section with changed lines:
```
        cmd = "boxes" #boxes.exe in this local dir (or if present in %PATH%), or boxes from $PATH in linux        
        for arg in vars(self.options):
            if arg != "output" and arg != "ids" and arg != "selected_nodes":
                #inkex.utils.debug(str(arg) + " = " + str(getattr(self.options, arg)))
                #fix behaviour of "original" arg which does not correctly gets interpreted if set to false
                if arg == "original" and str(getattr(self.options, arg)) == "false":
                    continue
                if arg in ("input_file", "tab", "labels"):
                    continue
                else:
                    cmd += ' --' + arg + '="' + str(getattr(self.options, arg)) + '"'   #doesn't hurt to add quotes around arguments
        cmd += " --output=" + box_file + " " #+ box_file #not needed it appears: we need to add box_file string twice in a row. Otherwise program executable throws an error
        cmd = cmd.replace("boxes --generator=", "boxes "))
```

Edit: 
Uninstalling/re-installing Inkscape and the FabLab Chemnitz tools didn't help for me.

Edit 2:
Seems for some text based arguments that they need to be between quotes to work.
Example:
`boxes fanhole --diameter=80 --mounting_holes=3 --mounting_holes_inset=5 --arms=10 --inner_disc=0.2 --style="CCW Swirl"`

**Comment by vmario89** [comment]
Hi, thanks for that enormous input! I will look into that after my holidays. I am working at a large release package for Inkscape 1.2.1 and definitely going to fix that boxes.py things to make in work properly on Windows and Linux. Give me 2 or 3 weeks more please :-) best regards, Mario

**Comment by vmario89** [comment]
https://github.com/eridur-de/mightyscape-1.2 is going to fix it - no more compilation needed. I will make that repo public shortly.
