### ISSUE TITLE
Incorrect Computation of Measurements for Box Maker - Generic Box extension from MightyScape

### ISSUE THREAD

**Issue by waj1051** [vmario89/mightyscape-1.X#4]
The data input interface for this extension states it is using Outside Dimensions. Not true. When the extension is calculating the SVG outputs / drawing the extension calcs add the material thickness to the input specs and creates a drawing that has incorrect dimensions. So, if the input for width is 100mm and material is 3mm the resulting drawing width is 106mm.

**Comment by vmario89** [comment]
Hi. Thanks for reporting. i pushed that to https://github.com/thierry7100/GenBox/issues/2

**Comment by vmario89** [comment]
i fixed this in a commit in newest mightyscape repo (not public yet, but soon) -> https://github.com/eridur-de/mightyscape-1.2
