### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by chatelao** [vmario89/mightyscape-1.X#5]
Hi everybody,

I love your idea, but have no clue how to install the collection in Inkscape. 

What about adding an "how to install" in the Readme.md?

**Comment by vmario89** [comment]
You should just read the readme. There you will find:

[](https://github.com/eridur-de/mightyscape-1.X#installation-documentation-and-examples)Installation, documentation and examples

The structure of this repo is intended the be easy. Just copy the complete MightyScape folder or the folders you want to your Inkscape's extension directory. You will find redundancies in this repo like node.exe (NodeJS). We did it this way to give easy possibilty to only pick the extensions you want (instead creating ~200 repositories). MightyScape does not work with any releases or feature branches. Just use "git clone" to get the recent commit from master branch. Please see at https://y.stadtfabrikanten.org/mightyscape-overview for installation tips like required python modules, file locations and other adjustments.
