### ISSUE TITLE
outputpro inkscape extension: error.

### ISSUE THREAD

**Issue by AlvesR0** [vmario89/mightyscape-1.X#8]
Sorry. that this is not the place to report the problem. but I didn't find an issue option in the inkscape outputpro extension repository.
I tried but got this error message. Is there a solution on how to solve it? I'm a windows user.
![image](https://user-images.githubusercontent.com/76485731/192120754-e1d4974b-6798-41cf-8141-caae6629f1e3.png)

**Comment by vmario89** [comment]
hi, no its the correct place to put :) if that error is shown you will need to install 

- a custom python environment, then
- pip for python, and then
- https://www.pythonguis.com/installation/install-pyqt-windows/
- finally you need to adjust your inkscape config to use that environment

more details at https://stadtfabrikanten.org/display/IFM/MightyScape+1.X+-+Introduction+and+Installation

**Comment by vmario89** [comment]
closed because stale
