### ISSUE TITLE
Who creates boxes.exe?

### ISSUE THREAD

**Issue by dokh** [vmario89/mightyscape-1.X#9]
As I've been troubleshooting boxes.py in mightyscape, I was wondering who owns boxes.exe?
The version I have seems to have some issues on my Windows 10.
Amongst them:

- Some box parameters aren't recognized
- Had modify boxes_proxy to use = instead of blank space between --parameter and value
- Had modify boxes_proxy to add quotes around parameter values to caputer text values with space in them

**Comment by vmario89** [comment]
closed because stale

**Comment by vmario89** [comment]
hi. boxes exe is going to be created by https://stadtfabrikanten.org/display/IFM/FabLab+Chemnitz+Boxes.py#expand-Showinstructioins. but this was in the past. as it seems we can use boxes.py without doing this complex stuff. i am working out a fix at the moment

**Comment by vmario89** [comment]
see also https://github.com/eridur-de/mightyscape-1.X/issues/3

**Comment by vmario89** [comment]
https://github.com/eridur-de/mightyscape-1.2 is going to fix it - no more compilation needed. I will make that repo public shortly.
